---
title: "Lecture 7 Workspace"
author: "Mario Giacomazzo"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=F)
options(scipen=999)
library(nycflights13) #Contains Flight Data
library(tidyverse)    #Essential Functions
library(knitr)        #kable() for HTML Tables
library(kableExtra)   #HTML Table Styling
```


```{r}
f.pipedream = 
  # Acknowledge the Original Data
  flights %>%
  
  # Input Original Data and Perform Mutations
  mutate(dep_hr=dep_time%/%100+(dep_time%%100)/60,
         sched_dep_hr=sched_dep_time%/%100+(sched_dep_time%%100)/60,
         arr_hr=arr_time%/%100+(arr_time%%100)/60,
         sched_arr_hr=sched_arr_time%/%100+(sched_arr_time%%100)/60,
         dep_delay_hr=dep_hr-sched_dep_hr,
         arr_delay_hr=arr_hr-sched_arr_hr,
         gain_hr=arr_delay_hr-dep_delay_hr,
         percent_gain_hr=percent_rank(gain_hr)) %>%
  
  #Input Modified Data and Select the Variables of Interest
  select(carrier,origin:distance,dep_delay_hr:percent_gain_hr) %>%
  
  #Input Modified Data and Sort According to Empirical %-iles
  arrange(desc(percent_gain_hr))
```

```{r,echo=F,results="asis"}
kable(head(f.pipedream,5)) %>%
  kable_styling(bootstrap_options="striped",full_width=F)
```

```{r}
f.pipedream2 = 
  # Acknowledge the Original Data
  flights %>%
  
  # Input Original Data and Perform Mutations
  mutate(dep_hr=dep_time%/%100+(dep_time%%100)/60,
         sched_dep_hr=sched_dep_time%/%100+(sched_dep_time%%100)/60,
         arr_hr=arr_time%/%100+(arr_time%%100)/60,
         sched_arr_hr=sched_arr_time%/%100+(sched_arr_time%%100)/60,
         dep_delay_hr=dep_hr-sched_dep_hr,
         arr_delay_hr=arr_hr-sched_arr_hr,
         gain_hr=arr_delay_hr-dep_delay_hr,
         percent_gain_hr=percent_rank(gain_hr)) %>%
  
  #Input Modified Data and Select the Variables of Interest
  select(carrier,origin:distance,dep_delay_hr:percent_gain_hr) %>%
  
  #Input Modified Data and Sort According to Empirical %-iles
  arrange(desc(percent_gain_hr)) %>%

  #Input Modified Data and Remove Flights Missing Air Time
  filter(!is.na(air_time))
```

```{r,echo=F,results="asis"}
kable(head(f.pipedream2,5)) %>%
  kable_styling(bootstrap_options="striped",full_width=F)
```

```{r}
ggplot(data=f.pipedream2,mapping=aes(x=gain_hr))+
  geom_density()
```


```{r}
f.pipedream3 = 
  
  # Acknowledge the Modified Data
  f.pipedream2 %>%
  
  # Filter Based on Gain Variable
  filter(abs(gain_hr)<10)
```

```{r,echo=F,results="asis"}
kable(head(f.pipedream3,5)) %>%
  kable_styling(bootstrap_options="striped",full_width=F)
```

```{r}
ggplot(data=f.pipedream3) +
  geom_histogram(aes(x=gain_hr),bins=50,color="black",
                 fill="deepskyblue1") + theme_minimal()
ggplot(data=f.pipedream3) + 
  geom_boxplot(aes(x="gain_hr",y=gain_hr),
                 color="black",fill="deepskyblue1")  +
                 theme_minimal()
```

```{r}
gain_hr.summary1 = summarize(f.pipedream3,
                      n=n(),
                      mean=mean(gain_hr,na.rm=T),
                      var=var(gain_hr,na.rm=T),
                      sd=sd(gain_hr,na.rm=T))

gain_hr.summary2 = 
  f.pipedream3 %>% 
  summarize(n=n(),
            min=min(gain_hr),
            Q1=quantile(gain_hr,0.25),
            Q2=quantile(gain_hr,0.5),
            Q3=quantile(gain_hr,0.75),
            max=max(gain_hr),
            IQR=Q3-Q1)
```

```{r,echo=F,results="asis"}
kable(gain_hr.summary1) %>%
  kable_styling(bootstrap_options="striped",full_width=F)
```

```{r,echo=F,results="asis"}
kable(gain_hr.summary2) %>%
  kable_styling(bootstrap_options="striped",full_width=F)
```

```{r}
ggplot(data=f.pipedream3) +
  geom_bar(aes(x=origin),fill="deepskyblue1")
```


```{r}
ggplot(data=f.pipedream3) +
  geom_boxplot(aes(x=origin,y=gain_hr),
               fill=c("red","white","blue"))
```

```{r}
group.summary1 = f.pipedream3 %>%
                 group_by(origin) %>%
                 summarize(count=n())

group.summary2 = 
  f.pipedream3 %>%
  group_by(origin) %>%
  summarize(
    n=n(),
    min=min(gain_hr),
    Q1=quantile(gain_hr,0.25),
    Q2=quantile(gain_hr,0.5),
    Q3=quantile(gain_hr,0.75),
    max=max(gain_hr),
    IQR=Q3-Q1,
    nLow=sum(gain_hr<Q1-1.5*IQR),
    propHigh=mean(gain_hr>Q3+1.5*IQR)
  ) %>%
  select(-IQR)
```

```{r,echo=F,results="asis"}
kable(group.summary1) %>%
  kable_styling(bootstrap_options="striped",full_width=F)
```

```{r,echo=F,results="asis"}
kable(group.summary2) %>%
  kable_styling(bootstrap_options="striped",full_width=F)
```


```{r}
ggplot(f.pipedream3) +
  geom_boxplot(aes(x=origin,y=gain_hr,fill=carrier))
```

```{r}
twogroup.summary1 = 
  f.pipedream3 %>% 
  group_by(origin,carrier) %>%
  summarize(
    n=n(),
    min=min(gain_hr),
    Q1=quantile(gain_hr,0.25),
    Q2=quantile(gain_hr,0.5),
    Q3=quantile(gain_hr,0.75),
    max=max(gain_hr)
  ) %>%
  arrange(origin,carrier)
```

```{r,echo=F,results="asis"}
kable(twogroup.summary1) %>%
  kable_styling(bootstrap_options="striped",full_width=F)
```


```{r}
accuracy<-
  f.pipedream3 %>%
  transmute(carrier,origin,
    accuracy=abs(dep_delay_hr)+abs(arr_delay_hr)) %>%
  group_by(carrier,origin) %>%
  summarize(n=n(),
    avg=mean(accuracy,na.rm=T),
    se=sd(accuracy,na.rm=T)/sqrt(n),
    low=avg-2*se,
    high=avg+2*se
  )
```


```{r}
head(arrange(accuracy,avg),5)
```

```{r}
head(arrange(accuracy,desc(avg)),5)
```

```{r}
ggplot(accuracy) +
  geom_point(aes(x=carrier,y=avg)) +
  geom_errorbar(aes(x=carrier,ymin=low,ymax=high)) +
  facet_grid(origin~.)
```

```{r}
ggplot(filter(accuracy,carrier!="OO")) +
  geom_point(aes(x=carrier,y=avg)) +
  geom_errorbar(aes(x=carrier,ymin=low,ymax=high)) +
  facet_grid(origin~.)
```



